### ISSUE TITLE
Cloning Fabricated Object

### ISSUE THREAD

**Issue by packocz** [mattaddy/SObjectFabricator#24]
Not a bug or issue, merely a question. I think I am missing something fundamental here. Any help or suggestions would be awesome, thanks for this great package!

I'm trying to extend sfab_FabricatedSObject and one of the things I'm needing is for any "set" to produce a new clone (I want to be building many records with common values and stuff). I noticed that there is a handy protected constructor that seemed like the best thing to use to preserve anything that's been set already, be it a field or relationship.
```
@testVisible
    protected sfab_FabricatedSObject(Type sType, List<sfab_FabricatedSObjectNode> nodes) {
        ...
    }
```
So I added another public method to the class to produce a clone. The intention being that my wrapper class will use this every time I add/change something to the fabricated object. 
```
public sfab_FabricatedSObject copy() {
        return new sfab_FabricatedSObject(this.sType, this.nodes.clone());
    }
```
However, things seem to break and the toSObject() method no longer works, failing with this error:
System.JSONException: Apex Type unsupported in JSON: Schema.SObjectField

I was wondering if you have any ideas what I'm doing wrong there. I tried to follow what's going on with the serialisation, but I could not figure it out at all.

I demonstrate the problem with this little script using the extended version of sfab_FabricatedObject where a1 gets generated fine, but a2 does not. The toSObject() call fails with the error above.
```
Account a1 = (Account) new sfab_FabricatedSObject(Account.class).set('Id', '001000000000001').toSObject();
System.debug(a1);

Account a2 = (Account) new sfab_FabricatedSObject(Account.class).set('Id', '001000000000001').copy().toSObject();
System.debug(a2);
```

**Comment by packocz** [comment]
Please forget this! I've finally found the problem and of course it's me 😊

In my copy method I was passing `this.nodes` as a whole (or clone) which is a map into the constructor of the new instance. Didn't realise this and this way I was inadvertently calling a wrong constructor! This `one public sfab_FabricatedSObject(Type sType, Map<String, Object> fields)` 

So making sure I work with a _list_ of nodes then calls the right one: `protected sfab_FabricatedSObject(Type sType, List<sfab_FabricatedSObjectNode> nodes)` and all is well.

**Comment by bobalicious** [comment]
Apologies for not having responded to this.  I didn't see the original
message coming in.

Glad you managed to resolve the issue you were having.
