### ISSUE TITLE
Can't set parent on contact object

### ISSUE THREAD

**Issue by martingaleh** [mattaddy/SObjectFabricator#25]
sfab_FabricatedSObject fc = new  sfab_FabricatedSObject(Contact.class...
sfab_FabricatedSObject fap = new  sfab_FabricatedSObject(Account.class...
fc.set('AccountId',fap) //doeesnt' work
fap.set('Contacts',fc) //doesn't work
fap.addChild('contacts',fc) works
fc.setParent('AccountId',fap) //doesnt' work
fc.addChild('AccountId',fap) //doesnt' work.  Shouldn't have, but just in case.

**Comment by bobalicious** [comment]
Sorry to hear you're having difficulties getting this to work.

I hope this clarifies things a little:

```
sfab_FabricatedSObject fc = new sfab_FabricatedSObject( Contact.class ).set( 'Name', 'The Contact' );
sfab_FabricatedSObject fap = new sfab_FabricatedSObject( Account.class ).set( 'Name', 'The Account' );

// Setting a parent requires you to set the relationship, not the Id
fc.set( 'Account', fap );
// or
fc.setParent( 'Account', fap );

// Setting a child requires you to 'add' them one by one
fap.add( 'Contacts', fc );
// or
fap.addChild( 'Contacts', fc );

// Or you can set them in a list
fap.set( 'Contacts', new List<sfab_FabricatedSObject>{ fc } );
// or
fap.setChildren( 'Contacts', new List<sfab_FabricatedSObject>{ fc } );
```

**Comment by bobalicious** [comment]
Also improved the docs to explicitly provide an example of setting the parent using another fabricated SObject.
- https://github.com/mattaddy/SObjectFabricator/commit/bdf66b2ea955b86deb89a3bcd2387379fc5b2eab

Examples already existed of adding children in this way, so not changes to docs to cover this.

**Comment by martingaleh** [comment]
I think its the trickiness of the salesforce documentation.  The field api name for this standard object is accountid, but the field name is account.  If you just did new contact(accountid = new account()), I think it works, so that's what iv'e been doing all my life and figured it would similarly work here.  Thanks for being so responsive.  this library is so much easier to use than others...

**Comment by bobalicious** [comment]
No worries, glad I could help, and that the library is useful!
